---
title: "DDP Assignment week 3<br>Plotly charts"
author: "Fabrice Zangl"
date: "November 11, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(ggplot2))
### getting the data
data("ToothGrowth")
head(ToothGrowth)
```

## Simple plot, but transfering from ggplot to plotly - THE CODE

```{r ggplotly_code, echo = TRUE, eval = FALSE, message = FALSE, warning=FALSE}
g <- ggplot(ToothGrowth, aes(factor(dose), len, fill = factor(dose))) 
g <- g + geom_boxplot()
g <- g + facet_grid(. ~ supp)
g <- g + theme_bw() 
g <- g + labs(title = "Look at this beautiful transformed ggplot")
g <- g + labs(x = "Dose")
g <- g + labs(y = "Tooth length")
(gg <- ggplotly(g))
```

## Simple plot, but transfering from ggplot to plotly - THE PLOT

```{r ggplotly_plot, echo = FALSE, eval = TRUE, message = FALSE, warning=FALSE}
g <- ggplot(ToothGrowth, aes(factor(dose), len, fill = factor(dose))) 
g <- g + geom_boxplot()
g <- g + facet_grid(. ~ supp)
g <- g + theme_bw() 
g <- g + labs(title = "Look at this beautiful transformed ggplot")
g <- g + labs(x = "Dose")
g <- g + labs(y = "Tooth length")
(gg <- ggplotly(g))
```

## 3D Scatterplot of the iris dataset - THE CODE

Now let's try and see, if we can look at the iris dataset in 3 dimensions, Let's first have a look at the code.

```{r 3D_code, echo = TRUE, eval = FALSE, message = FALSE}
data("iris")
plot_ly(x = iris$Petal.Length, y = iris$Petal.Width, z = iris$Sepal.Length,
        type = "scatter3d", mode = "markers", color = iris$Species)
```

## 3D Scatterplot of the iris dataset - THE PLOT

```{r 3D_plot, echo = FALSE, eval = TRUE, message = FALSE}
data("iris")
plot_ly(x = iris$Petal.Length, y = iris$Petal.Width, z = iris$Sepal.Length,
        type = "scatter3d", mode = "markers", color = iris$Species)
```

## Thank you

*I hope you enjoyed this graphs*